name: "L0p4Map"
version: "1.0.0"
slug: l0p4map
description: "Network monitoring & topology visualization — ARP discovery, nmap scan, real-time graph"
arch:
  - amd64
url: "https://github.com/HaxL0p4/L0p4Map"
boot: "manual"
host_network: true
privileged:
  - NET_ADMIN
ingress: true
ingress_port: 8099
map:
  - share:rw
options:
  target: ""
  interface: ""
  interval: 3600
schema:
  target: "str?"
  interface: "str?"
  interval: "int"