name: "L0p4Map"
version: "1.0.0"
slug: l0p4map
description: "Network monitoring & topology visualization"
arch:
  - amd64
init: false
ingress: true
ingress_port: 8099
map:
  - share:rw
options:
  target: ""
  interval: 3600
schema:
  target: "str?"
  interval: "int"